title = "Gaia Sky"
baseURL =  ""
languageCode = "en-us"
theme = [ "hugo-easy-gallery" ]
preserveTaxonomyNames = true
enableRobotsTXT = true
uglyurls = false
enableGitInfo = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[services]
  [services.rss]
    limit = 50

[menu]

  [[menu.header]]
    weight = -1
    name = "Home"
    pageRef = "/"
  [[menu.header]]
    weight = 1
    name = "News"
    pageRef = "news"
  [[menu.header]]
    weight = 2
    name = "Gallery"
    pageRef = "media"
  [[menu.header]]
    weight = 3
    name = "Downloads"
    pageRef = "downloads"
  [[menu.header]]
    weight = 4
    name = "Docs"
    url = "http://docs.gaiasky.space"
  [[menu.header]]
    weight = 5
    name = "Resources"
    pageRef = "resources"
  [[menu.header]]
    weight = 6
    name = "Contact"
    pageRef = "contact"
  [[menu.header]]
    weight = 7
    name = " "
    pre = '<i class="fa-solid fa-magnifying-glass"></i>'
    pageRef = "search"


# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "2 Jan 2006"
  version = "3.6.6"
  versionFlat = "3_6_6"
  versionRevision = "3.6.6.caf73d2de"
  releaseDate = 2025-01-24


  [params.meta]
    description = "Homepage of Gaia Sky, an open source 3D universe platform"
    author = "tsagrista"
    favicon = true

  [params.slider]
    enable = true
    title = "Gaia Sky"
    subtitle = "Open source 3D Universe visulaization platform with support for a billion objects"
    buttonTitle = "Download Gaia Sky"
    buttonurl = "downloads"

  [params.wrapper]
    enable = true
    title = "Explore the cosmos"
    italic = "**Gaia Sky** is a real-time, 3D, astronomy visualisation platform for desktop and VR that runs on *Windows*, *Linux*, and *macOS*. Open source and libre."
    paragraph = "Gaia Sky enables the exploration of our Universe by means of scientific datasets. The software includes an integrated dataset manager that grants access to several [cutting-edge astronomical catalogs](/resources/datasets) such as the Gaia DR1/2/3 star catalogs, SDSS galaxies, or the nearby galaxies catalog. It is developed in the framework of [ESA](http://www.esa.int/ESA)'s [Gaia mission](http://sci.esa.int/gaia) to chart about 1 billion stars of our Galaxy in the Gaia group of the [Astronomisches Rechen-Institut](http://www.ari.uni-heidelberg.de/) ([ZAH](http://www.zah.uni-heidelberg.de/), [Universität Heidelberg](http://www.uni-heidelberg.de/)). Explore the cosmos without leaving the comfort of your home!"
    image = "img/special/exo001.png"

  [params.news]
    enable = true
    title = "News"
    subtitle = "Latest blog posts, news, features, and dev stories"

  [params.postslist]
    enable = true
    title = "News (full list)"
    subtitle = "Condensed list of all news and dev stories"

  [params.datasets]
    enable = true
    title = "Worlds of data"
    content = "We have curated a long list of scientific datasets for you to explore in Gaia Sky. Planets, moons, asteroids, stars, nebulae, galaxies, quasars, black holes, star clusters, iso-density maps, virtual textures, and much, much more!<br>Use the in-app dataset manager to pick and choose the datasets you want to explore."
    [params.datasets.button]
      caption = "Available datasets"
      url = "resources/datasets"
      pre = '<i class="fa-solid fa-database"></i>'

  [params.media]
    enable = true
    title = "Gallery"
    subtitle = "Screenshots, videos, and more"

  [params.downloads]
    enable = true
    title = "Downloads"
    subtitle = "Get Gaia Sky for your system"

  [params.resources]
    enable = true
    title = "Resources"
    subtitle = "Datasets, learning material, icons, etc."

  [params.contact]
    enable = true
    title = "Contact"
    subtitle = "Get in touch with us"

  [[params.social]]
    name = "RSS"
    url = "/index.xml"
    icon = "fa-solid fa-square-rss"
  [[params.social]]
    name = "BlueSky"
    url = "https://bsky.app/profile/gaiasky.bsky.social"
    icon = "fa-brands fa-square-bluesky"
  [[params.social]]
    name = "Mastodon"
    url = "https://mastodon.social/@jumpinglangur"
    icon = "fa-brands fa-mastodon"
  [[params.social]]
    name = "YouTube"
    url = "https://youtube.com/@gaiaskydev"
    icon = "fa-brands fa-square-youtube"
  [[params.social]]
    name = "Email"
    url = "mailto:tsagrista@ari.uni-heidelberg.de?subject=Gaia Sky"
    icon = "fa-solid fa-envelope"


  [[params.ack]]
    name = "ZAH"
    url = "https://zah.uni-heidelberg.de"
    img = "img/zah.png"
  [[params.ack]]
    name = "DLR"
    url = "https://www.dlr.de"
    img = "img/dlr.png"
  [[params.ack]]
    name = "BMWK"
    url = "https://www.bmwk.de"
    img = "img/bwt.png"

[pagination]
  disableAliases = false
  pagerSize = 8
  path = 'page'

# Properties of the markdown renderer.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
