title = "Gaia Sky"
baseURL = "gaiasky"
languageCode = "en-us"
theme = "gaiasky"

[menu]

  [[menu.header]]
    weight = 2
    name = "News"
    url = "/news"
  [[menu.header]]
    weight = 3
    name = "Screenshots"
    url = "/screenshots"
  [[menu.header]]
    weight = 4
    name = "Download"
    url = "/downloads"
  [[menu.header]]
    weight = 5
    name = "Docs"
    url = "https://gaia.ari.uni-heidelberg.de/gaiasky/docs"
  [[menu.header]]
    weight = 6
    name = "Sources"
    url = "https://codeberg.org/gaiasky/gaiasky"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "News"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 Jan 2006"


  [params.slider]
    enable = true
    title = "Gaia Sky"
    subtitle = "3D Universe platform with support for a billion stars"

  [params.wrapper]
    enable = true
    title = "Explore real scientific data"
    italic = "Gaia Sky is a real-time, 3D, astronomy visualisation software for desktop and VR that runs on Windows, Linux and macOS. Open source and libre."
    paragraph = "It is developed in the framework of ESA's Gaia mission to chart about 1 billion stars of our Galaxy in the Gaia group of the Astronomisches Rechen-Institut (ZAH, Universität Heidelberg). The software includes an integrated dataset manager that enables the download and activation of several astronomical datasets such as Gaia, SDSS, or NGC."

  [params.blog]
    enable = true
    title = "Gaia Sky blog"
    subtitle = "Latest news, features and dev stories"

  [params.feature]
    enable = true
    title = "Features"
    content = "Free and open source, supports high object counts, VR-ready, proper motion explorer, exoplanets and planetary surfaces, eclipse representation, 3D profiles, domemaster and planetarium modes, load your own datasets, real time filters and effects, SAMP aware, keyframed camera paths, scriptable and extensible."
    [params.feature.button]
      caption = "See more"
      url = "/screenshots"

  [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Drop us a line"
    subtitle = "Use the contact form below"
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Contact info"
      address = "Astronomisches Rechen-Institut, Mönchhofstr. 12-14 69120, Heidelberg"
      email = "Email: tsagrista@ari.uni-heidelberg.de"
